import { describe, expect, it } from "vitest";
import { resolve } from "node:path";
import { AS_QUOTED } from "@sq/shared";
import { parseQuotation } from "./index.js";
import { parseNumeric, cleanFloat } from "./read-workbook.js";
import { looksLikeSku, tidySku, tierQuantityFromHeader, headerRole } from "./heuristics.js";
import { normalisePaymentTerms, parseLeadTimeDays } from "./metadata.js";

const fixture = (n: number) => resolve(import.meta.dirname, "../../../../fixtures", `quotation_${n}.xlsx`);

/** 1-4 came with the brief; 5-10 are generated by `pnpm fixtures`. */
const ALL_FIXTURES = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

describe("cell value cleanup", () => {
  it("snaps Excel float noise back to the number a human wrote", () => {
    expect(cleanFloat(23987.999999999996)).toBe(23988);
    expect(cleanFloat(89954.99999999999)).toBe(89955);
  });

  it("reads money the way people type it", () => {
    expect(parseNumeric("$1,234.50")).toBe(1234.5);
    expect(parseNumeric("USD 12.30")).toBe(12.3);
    expect(parseNumeric("(45.00)")).toBe(-45);
    expect(parseNumeric("1.234,56")).toBe(1234.56);
    expect(parseNumeric("")).toBeNull();
    expect(parseNumeric("N/A")).toBeNull();
  });

  it("tells a grouping comma from a decimal one by its shape", () => {
    // "5,000" as a quantity used to come back as 5, because a comma with nothing
    // to compare it against was read as a decimal point. An order for five units.
    expect(parseNumeric("5,000")).toBe(5000);
    expect(parseNumeric("1,234,567")).toBe(1234567);
    expect(parseNumeric("11,32")).toBe(11.32);
    expect(parseNumeric("1,5")).toBe(1.5);
    // A leading zero settles it: nobody writes nought thousand.
    expect(parseNumeric("0,750")).toBe(0.75);
  });

  it("reads a number typed with a non-breaking space between the thousands", () => {
    expect(parseNumeric("5\u00a0000")).toBe(5000);
  });
});

describe("looksLikeSku", () => {
  it("accepts real catalog codes including the typo'd ones", () => {
    for (const sku of ["PHS001-OBS-XL", "OPP029-ICB-36-26", "0PP027-FNV-28-30", "EKA03-GLW-M", "MBOO2-LGR-S"]) {
      expect(looksLikeSku(sku), sku).toBe(true);
    }
  });

  it("rejects the footer and metadata values that sit in the same columns", () => {
    // This predicate is what decides which rows are line items, so a false
    // positive here silently turns a payment term into a product.
    for (const text of ["30/70", "90 days", "USD", "2026-02-05", "Contour Jr", "TOTAL", "1000"]) {
      expect(looksLikeSku(text), text).toBe(false);
    }
  });

  it("survives the typography a code picks up on its way through a document", () => {
    // An autocorrected hyphen or a leftover footnote marker used to fail the
    // structural test, and a couple of failures in a row end the data region —
    // so one mangled code could truncate the rest of the price list.
    expect(looksLikeSku("MC001\u2013GLW\u2013M")).toBe(true); // en-dash
    expect(looksLikeSku("MC001\u2014GLW\u2014M")).toBe(true); // em-dash
    expect(looksLikeSku("MH010-GLW-L*")).toBe(true); // footnote marker
    expect(tidySku("MC001\u2013GLW\u2013M")).toBe("MC001-GLW-M");
    expect(tidySku("  MH010-GLW-L*  ")).toBe("MH010-GLW-L");

    // Repairing typography must not become "accept anything": a row with spaces
    // in the code is indistinguishable from prose, and prose is not an order.
    expect(looksLikeSku("MR007 LGR M")).toBe(false);
    expect(looksLikeSku("SAMPLE ONLY")).toBe(false);
  });
});

describe("header interpretation", () => {
  it("reads the quantity out of a tier column header", () => {
    expect(tierQuantityFromHeader("Unit FOB Price - Qty 1000")).toBe(1000);
    expect(tierQuantityFromHeader("Unit FOB Price - Qty 5,000")).toBe(5000);
    expect(tierQuantityFromHeader("Unit price")).toBeNull();
  });

  it("prefers the most specific label so 'Total price' is not a unit price", () => {
    expect(headerRole("Total price")).toBe("line_total");
    expect(headerRole("Unit price")).toBe("unit_price");
    expect(headerRole("FOB Price")).toBe("unit_price");
  });
});

describe("terms parsing", () => {
  it("normalises however the file writes a milestone split", () => {
    expect(normalisePaymentTerms("30/70")).toBe("30/70");
    expect(normalisePaymentTerms("T/T 40 / 60")).toBe("40/60");
    expect(normalisePaymentTerms("33/33/33")).toBe("33/33/33");
    expect(normalisePaymentTerms("100% upfront")).toBe("100");
    expect(normalisePaymentTerms("net 30")).toBeNull();
  });

  it("reads lead times with and without units", () => {
    expect(parseLeadTimeDays("90 days")).toBe(90);
    expect(parseLeadTimeDays("60")).toBe(60);
    expect(parseLeadTimeDays("45 天")).toBe(45);
  });
});

describe("quotation_1: preamble, merged cells, stacked tier blocks", () => {
  it("finds the table under 15 rows of letterhead and reads both tiers", async () => {
    const result = await parseQuotation(fixture(1));

    expect(result.layout.tierLayout).toBe("row_blocks");
    expect(result.tiers).toEqual([500, 5000]);
    expect(result.lines).toHaveLength(40);
    expect(result.metadata.supplierName).toBe("Thai Textiles");
    expect(result.metadata.quotationDate).toBe("2026-01-01");

    const first = result.lines[0]!;
    expect(first.rawSku).toBe("PHS001-OBS-XL");
    expect(first.quantity).toBe(500);
    expect(first.unitPrice).toBe(7.92);
    // The sheet stores this as a formula; we take the cached result.
    expect(first.lineTotal).toBe(3960);

    // The same SKU appears again lower down at the higher volume and cheaper.
    const atVolume = result.lines.find((l) => l.rawSku === "PHS001-OBS-XL" && l.tierQuantity === 5000);
    expect(atVolume?.unitPrice).toBe(7);
  });
});

describe("quotation_2: tiers as columns, no quantity column, footer terms", () => {
  it("takes each tier's quantity from its column header", async () => {
    const result = await parseQuotation(fixture(2));

    expect(result.layout.tierLayout).toBe("columns");
    expect(result.tiers).toEqual([1000, 5000]);
    expect(result.metadata.paymentTerms).toBe("30/70");
    expect(result.metadata.leadTimeDays).toBe(90);
  });

  it("emits no line where the sheet declined to quote, rather than a zero", async () => {
    const result = await parseQuotation(fixture(2));

    // 25 SKUs at two tiers, less the two that carry no 5000 price at all.
    expect(result.lines).toHaveLength(48);

    for (const sku of ["OJ3008-SRD-XL", "OPP012-OBS-32-28"]) {
      const tiers = result.lines.filter((l) => l.rawSku === sku).map((l) => l.tierQuantity);
      expect(tiers, sku).toEqual([1000]);
    }
  });
});

describe("quotation_3: two sheets as tiers, discount column, TOTAL row", () => {
  it("applies the discount and ignores the totals row", async () => {
    const result = await parseQuotation(fixture(3));

    expect(result.layout.tierLayout).toBe("sheets");
    expect(result.lines).toHaveLength(46);
    expect(result.metadata.supplierName).toBe("Prestige Manufacturing Co., Ltd.");
    expect(result.metadata.paymentTerms).toBe("40/60");
    expect(result.metadata.leadTimeDays).toBe(60);

    const discounted = result.lines.find((l) => l.rawSku === "AT006-DWD-L" && l.sheetName === "Quote 1")!;
    expect(discounted.listUnitPrice).toBe(6.25);
    expect(discounted.discountPct).toBe(10);
    expect(discounted.unitPrice).toBe(5.625);
    // Multiplying before rounding: 5.63 x 5000 would overstate this by $25.
    expect(discounted.lineTotal).toBe(28125);
    expect(discounted.totalMismatch).toBe(false);
  });

  it("offers only the quantity that is genuinely a volume tier", async () => {
    const result = await parseQuotation(fixture(3));
    // Seventeen distinct quantities appear in the file; only 5000 is a tier.
    expect(result.tiers).toEqual([5000]);
    expect(result.suggestedTier).toBe(5000);
  });
});

describe("quotation_4: Chinese headers that name the wrong columns", () => {
  it("trusts the arithmetic over the labels and says so", async () => {
    const result = await parseQuotation(fixture(4));
    const sheet = result.layout.sheets[0]!;

    const quantity = sheet.columns.find((c) => c.role === "quantity")!;
    const price = sheet.columns.find((c) => c.role === "unit_price")!;

    // The header on the quantity column reads "unit price" and vice versa.
    expect(quantity.header).toBe("单价");
    expect(price.header).toBe("数量");

    expect(result.warnings.join(" ")).toContain("but its values are quantity");

    const first = result.lines[0]!;
    expect(first.rawSku).toBe("AT008-ICB-L");
    expect(first.quantity).toBe(1000);
    expect(first.unitPrice).toBe(45);
  });

  it("reports no tier when the file is a mixed basket", async () => {
    const result = await parseQuotation(fixture(4));
    expect(result.tiers).toEqual([]);
    expect(result.suggestedTier).toBe(AS_QUOTED);
  });

  // quotation_9 offers tiers *and* suggests none of them, because neither covers
  // enough of the sheet. That combination is what made the review screen render a
  // file that parsed perfectly as an empty table: a client treating AS_QUOTED as
  // an ordinary tier filters every row away.
  it("can offer tiers while still suggesting none of them", async () => {
    const result = await parseQuotation(fixture(9));
    expect(result.tiers).toEqual([1000, 2000]);
    expect(result.suggestedTier).toBe(AS_QUOTED);
    expect(result.lines.length).toBeGreaterThan(0);

    // The quantities the file quotes are not confined to the tiers it offers,
    // which is precisely why no single tier could be suggested.
    const quantities = new Set(result.lines.map((l) => l.tierQuantity));
    expect(quantities.has(5000)).toBe(true);
  });
});

describe("robustness", () => {
  it("fails loudly rather than silently on a file with no table", async () => {
    await expect(parseQuotation(Buffer.from("not a spreadsheet"))).rejects.toThrow();
  });

  it("never returns a line without a positive price and quantity", async () => {
    for (const n of ALL_FIXTURES) {
      const result = await parseQuotation(fixture(n));
      for (const line of result.lines) {
        expect(line.unitPrice, `q${n} ${line.rawSku}`).toBeGreaterThan(0);
        expect(line.quantity, `q${n} ${line.rawSku}`).toBeGreaterThan(0);
      }
    }
  });
});

/**
 * Fixtures 5 to 10 are ours, and each one exists to break a specific assumption:
 * merged multi-row headers and summary rows, numbers stored as text, mangled
 * codes, a table hidden on a third sheet, headers that name the wrong column, and
 * duplicate lines with holes in the pricing.
 *
 * Asserted as a floor on what must survive rather than an exact transcript. A
 * parser that gets *more* out of these files should not have to update a test to
 * prove it, but one that quietly starts dropping half a price list must fail.
 */
describe("the awkward files", () => {
  const EXPECTED: Record<number, { minLines: number; tiers?: number[]; leadTime?: number; terms?: string }> = {
    5: { minLines: 24, tiers: [1000, 5000] },
    6: { minLines: 11, terms: "50/50" },
    7: { minLines: 9, leadTime: 52, terms: "100" },
    8: { minLines: 11 },
    9: { minLines: 12, leadTime: 42, terms: "40/60" },
    10: { minLines: 20, tiers: [1000, 5000], leadTime: 33, terms: "30/40/30" },
  };

  for (const [n, want] of Object.entries(EXPECTED)) {
    it(`reads quotation_${n}`, async () => {
      const result = await parseQuotation(fixture(Number(n)));
      expect(result.lines.length).toBeGreaterThanOrEqual(want.minLines);
      if (want.tiers) expect(result.tiers).toEqual(want.tiers);
      if (want.leadTime) expect(result.metadata.leadTimeDays).toBe(want.leadTime);
      if (want.terms) expect(result.metadata.paymentTerms).toBe(want.terms);
    });
  }

  it("keeps the summary rows out of the order", async () => {
    // SUBTOTAL, Freight and TOTAL sit inside the table in quotation_5. Buying a
    // product called TOTAL is the classic way to get this wrong.
    const result = await parseQuotation(fixture(5));
    const codes = result.lines.map((l) => l.rawSku.toUpperCase());
    for (const junk of ["SUBTOTAL", "TOTAL", "FREIGHT (EST.)"]) {
      expect(codes).not.toContain(junk);
    }
  });

  it("reads a quantity written with a thousands separator as thousands", async () => {
    // Every quantity in quotation_6 is text: "5,000", "2 500", "$41.84".
    const result = await parseQuotation(fixture(6));
    expect(result.lines.every((l) => l.quantity >= 1000)).toBe(true);
    expect(result.lines.some((l) => l.quantity === 5000)).toBe(true);
  });

  it("recovers the rows whose codes were mangled in transit", async () => {
    // The en-dash and footnote-marker rows used to end the data region, taking
    // everything below them with it: 3 lines survived out of 11.
    const result = await parseQuotation(fixture(7));
    const codes = result.lines.map((l) => l.rawSku);
    expect(codes).toContain("MC001-GLW-M"); // was MC001–GLW–M
    expect(codes).toContain("MH010-GLW-L"); // was MH010-GLW-L*
    // Codes that are not in the catalogue still have to reach matching, so they
    // can be reported as unmatched rather than disappear.
    expect(codes).toContain("ZZQ999-XXX-M");
  });

  it("finds the table when it is on the third sheet, indented and pushed down", async () => {
    const result = await parseQuotation(fixture(8));
    expect(result.lines.length).toBeGreaterThanOrEqual(11);
    expect(result.lines.every((l) => l.sheetName === "Pricing")).toBe(true);
  });

  it("trusts the arithmetic over headers that name the wrong column", async () => {
    // Header says price then quantity; the columns hold quantity then price.
    const result = await parseQuotation(fixture(9));
    for (const line of result.lines) {
      expect(line.quantity).toBeGreaterThanOrEqual(1000);
      expect(line.unitPrice).toBeLessThan(1000);
    }
  });
});
